### ISSUE TITLE
Where is the official API documentation?

### ISSUE THREAD

**Issue by AryehGielchinsky** [sh0oki/israel-rail-api#1]
Hi, do you know where the official Israel Train API documentation is? I couldn't find it Googling, and their customer service doesn't know what an API is. thanks

**Comment by sh0oki** [comment]
There is no official api :)
This project is a python implementation of the backend api used by their website. Not sure if it still works, it’s been a couple of years since I used this.
________________________________
From: Aryeh Gielchinsky ***@***.***>
Sent: Sunday, April 24, 2022 3:21:13 PM
To: sh0oki/israel-rail-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sh0oki/israel-rail-api] Where is the official API documentation? (Issue #1)


Hi, do you know where the official Israel Train API documentation is? I couldn't find it Googling, and their customer service doesn't know what an API is. thanks
