### ISSUE TITLE
ssl certificate changed

### ISSUE THREAD

**Issue by Frostswing** [sh0oki/israel-rail-api#2]
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.rail.co.il', port=443): Max retries exceeded with url: /apiinfo/api/Plan/GetRoutes?OId=3600&TId=680&Date=20230605&Hour=0900&isGoing=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by sh0oki** [comment]
Hey @Frostswing, thanks for reporting this!
You're correct and this happens due to a missing behavior in Python's CA list (see https://github.com/python/cpython/issues/62817). 
Specifically, the intermediate certificate "GeoTrust RSA CA 2018" is not sent when accessing the Israeli rail website, failing the trust chain Python tries to establish.

I'll add this certificate manually so the script can continue working.

**Comment by sh0oki** [comment]
Unfortunately I see that the API has changed, so even after ignoring the SSL error this won't work.
If you want, I welcome you to fix the API to match the new website, in which the requests look somewhat like this:

```
https://israelrail.azurefd.net/rjpa-prod/api/v1/timetable/searchTrainLuzForDateTime?fromStation=3600&toStation=680&date=2023-06-05&hour=14:15&scheduleType=1&systemType=2&languageId=Hebrew
```

Thanks!

**Comment by Frostswing** [comment]
Thanks @sh0oki !
i noticed this happens since api change as you said

you say the new api url is as the following?
where did you get this new api url? Now it requests an api key

**Comment by sh0oki** [comment]
From the website :)

To fix this, set these consts in api.py: 

```python
API_BASE = 'https://israelrail.azurefd.net/rjpa-prod/api/v1'
API_KEY = "4b0d355121fe4e0bb3d86e902efe9f20"
DEFAULT_HEADERS = {'User-Agent': USER_AGENT,
                   "ocp-apim-subscription-key": API_KEY}
```

The response format is a bit different now, but the same general idea. 

I hope this helps!
